name: Setup go/xgo & engine
description: Setup go/xgo & engine.
inputs:
  go-version:
    description: 'Go version to setup'
    required: false
    default: '1.24.0'
  xgo-version:
    description: 'XGo version to setup'
    required: false
    default: '1.5.0'
runs:
  using: "composite"
  steps:
    - name: Set up Go/XGo
      uses: goplus/setup-xgo@v1
      with:
        go-version: ${{ inputs.go-version }}
        xgo-version: ${{ inputs.xgo-version }}

    - name: Get GOPATH
      id: gopath
      run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Godot engine files
      id: cache-godot
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.gopath.outputs.GOPATH }}/bin/gdspx*
          ${{ steps.gopath.outputs.GOPATH }}/bin/gdspxrt*
          ${{ steps.gopath.outputs.GOPATH }}/bin/runtime.gdextension
          ~/.local/share/godot/export_templates
          ~/Library/Application Support/Godot/export_templates
          ~/AppData/Roaming/Godot/export_templates
        key: spx-godot-${{ runner.os }}-${{ hashFiles('cmd/gox/template/version') }}
        restore-keys: |
          spx-godot-${{ runner.os }}-

    - name: Setup engine (cache miss)
      if: steps.cache-godot.outputs.cache-hit != 'true'
      run: |
        make setup-web-full
      shell: bash
      
    - name: Setup web engine (cache hit)
      if: steps.cache-godot.outputs.cache-hit == 'true'
      run: |
        make setup-web MODE=normal
      shell: bash
