name: Setup go/xgo & engine
description: Setup go/xgo & engine.
inputs:
  go-version:
    description: 'Go version to setup'
    required: false
    default: '1.24.0'
  xgo-version:
    description: 'XGo version to setup'
    required: false
    default: '1.5.0'
runs:
  using: "composite"
  steps:
    - name: Set up Go/XGo
      uses: goplus/setup-xgo@v1
      with:
        go-version: ${{ inputs.go-version }}
        xgo-version: ${{ inputs.xgo-version }}

    - name: Prepare engine
      run: make setup
      shell: bash

