name: Test Godot project
description: Run the test Godot project.
runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: go build -v $(go list ./... | grep -v /internal/webffi)

    - name: Test
      shell: bash
      run: go test -v $(go list ./... | grep -v /internal/webffi)

    - name: GenGo
      shell: bash
      run: xgo go ./...

    - name: Run test demo
      shell: bash
      run: spx run -path="test/CI" -headless=true 2>&1 | tee cilog.txt 

    - name: Check test result
      shell: bash
      run: |
        if grep -q "===>SpxCIRunSucc" cilog.txt; then
          echo "test success"
          rm -f cilog.txt
        else
          echo "test failed: not found success mark"
          cat cilog.txt
          rm -f cilog.txt
          exit 1
        fi

    - name: Run test demo in interpreted mode
      shell: bash
      run: |
        spx runi -path="test/CI" -headless=true 2>&1 | tee cilog_interpreted_mode.txt 

    - name: Check test result in interpreted mode
      shell: bash
      run: |
        if grep -q "===>SpxCIRunSucc" cilog_interpreted_mode.txt; then
          echo "test success"
          rm -f cilog_interpreted_mode.txt
        else
          echo "test failed: not found success mark"
          cat cilog_interpreted_mode.txt
          rm -f cilog_interpreted_mode.txt
          exit 1
        fi